name: Automated Comment Bot

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on bug issues
        if: contains(github.event.issue.labels.*.name, "bug")
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you. We will fix it"
            })
      
      - name: Comment on feature issues
        if: contains(github.event.issue.labels.*.name, "feature")
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you, we will consider to include this feature."
            })
      
      - name: Comment on unlabeled issues
        if: github.event.issue.labels.length == 0
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you for your contribution!"
            })